# Generated by Django 3.0.5 on 2021-12-20 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 20)),
        ),
    ]
